---
- name: Provisionning webservers group
  hosts: webservers
  tasks:
    - name: Upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install packages
      apt:
        name:
          - apt-transport-https
          - build-essential
          - curl
          - fail2ban
          - git
          - htop
          - ntp
          - ufw
          - vim
        state: latest
        update_cache: yes
        autoremove: yes
        autoclean: yes
      notify:
        - start ntp
        - start fail2ban

    - name: Remove snap
      apt:
        name:
          - snapd
          - snap
        state: absent
        purge: true

    - name: Configure ufw defaults
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - direction: incoming
          policy: deny
        - direction: outgoing
          policy: allow

    - name: Configure ufw rules
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        src: "{{ item.src }}"
      loop:
        - rule: 'limit'
          port: '22'
          proto: 'tcp'
          src: 'any'
        - rule: 'deny'
          port: '80'
          proto: 'tcp'
          src: 'any'
        - rule: 'deny'
          port: '443'
          proto: 'tcp'
          src: 'any'
        - rule: 'allow'
          port: '6379'
          proto: 'tcp'
          src: '10.0.0.2'
        - rule: 'allow'
          port: '6379'
          proto: 'tcp'
          src: '10.0.0.3'


    - name: Enable ufw
      ufw:
        state: enabled

  handlers:
    - name: start ntp
      service:
        name: ntp
        state: started
        enabled: yes

    - name: start fail2ban
      service:
        name: fail2ban
        state: started
        enabled: yes
